#! /bin/sh

# mod-wsgi.{load,conf} renamed to wsgi.{load,conf} in 1.3-2 / 2.0~c4-2
version_with_old_module_name() {
    dpkg --compare-versions "$1" lt-nl "1.3-2" && return 0
    dpkg --compare-versions "$1" lt-nl "2.0~c4-2" && dpkg --compare-versions "$1" gt-nl "2.0~c1" && return 0
    return 1
}
restore_mod_wsgi() {
    a2dismod wsgi || true
    # downgrading to package with old module name -- we have to restore pseudo conffile
    echo "LoadModule wsgi_module /usr/lib/apache2/modules/mod_wsgi.so" > /etc/apache2/mods-available/mod-wsgi.load
    if [ -e /etc/apache2/mods-available/wsgi.conf ]; then
        mv /etc/apache2/mods-available/wsgi.conf /etc/apache2/mods-available/mod-wsgi.conf
    fi
    if [ -e /etc/apache2/mods-available/wsgi.load ]; then
        rm -f /etc/apache2/mods-available/wsgi.load
    fi
}
if version_with_old_module_name $2; then
    test ! -e /etc/apache2/mods-available/mod_wsgi.load && restore_mod_wsgi
fi


if [ "$1" = "purge" -o "$1" = "remove" ]; then
    # remove pseudo conffile
    test -e /etc/apache2/mods-available/wsgi.load && rm -f /etc/apache2/mods-available/wsgi.load
fi
if [ "$1" = "purge" -a -e /etc/apache2/mods-available/wsgi.conf ]; then
    # remove conffile
    rm -f /etc/apache2/mods-available/wsgi.conf
fi

#DEBHELPER#

exit 0
